all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.." 
run:
#	java -classpath "../.." s4.B193313/Hello
#	java -classpath "../.." s4.B193313/Frequencer
#	java -classpath "../.." s4.B193313/InformationEstimator
	java -classpath "../.." s4.B193313/TestCase

